// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopGiay.Data;

#nullable disable

namespace ShopGiay.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125092741_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopGiay.Models.Chucvu", b =>
                {
                    b.Property<int>("MaCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCv"));

                    b.Property<double?>("HeSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCv")
                        .HasName("PK__CHUCVU__27258E765E11D519");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("ShopGiay.Models.Cthoadon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthd"));

                    b.Property<int?>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaK")
                        .HasColumnType("int");

                    b.Property<int>("MaKc")
                        .HasColumnType("int");

                    b.Property<int>("MaMh")
                        .HasColumnType("int");

                    b.Property<int>("MaMs")
                        .HasColumnType("int");

                    b.Property<short?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaCthd")
                        .HasName("PK__CTHOADON__1E4FA771F512215C");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaK");

                    b.HasIndex("MaKc");

                    b.HasIndex("MaMh");

                    b.HasIndex("MaMs");

                    b.ToTable("CTHOADON");
                });

            modelBuilder.Entity("ShopGiay.Models.Cuahang", b =>
                {
                    b.Property<int>("MaCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCh")
                        .HasName("PK__CUAHANG__27258E00A1FDB92B");

                    b.ToTable("CUAHANG");
                });

            modelBuilder.Entity("ShopGiay.Models.Danhgium", b =>
                {
                    b.Property<int>("MaDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDg"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaMh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDG")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.HasKey("MaDg")
                        .HasName("PK__DANHGIA__27258660CC45A924");

                    b.HasIndex("MaMh");

                    b.HasIndex(new[] { "MaKh", "MaMh" }, "UQ__DANHGIA__A55792EC175A939E")
                        .IsUnique();

                    b.ToTable("DANHGIA");
                });

            modelBuilder.Entity("ShopGiay.Models.Diachi", b =>
                {
                    b.Property<int>("MaDc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDc"));

                    b.Property<string>("DiaChi1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChi");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDc")
                        .HasName("PK__DIACHI__2725866443F55466");

                    b.HasIndex("MaKh");

                    b.ToTable("DIACHI");
                });

            modelBuilder.Entity("ShopGiay.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("Ngay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaHd")
                        .HasName("PK__HOADON__2725A6E002FDC379");

                    b.HasIndex("MaKh");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("ShopGiay.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E036AC910");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("ShopGiay.Models.Kichco", b =>
                {
                    b.Property<int>("MaKc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKc"));

                    b.Property<double>("GiaTriKc")
                        .HasColumnType("float")
                        .HasColumnName("GiaTriKC");

                    b.HasKey("MaKc")
                        .HasName("PK__KICHCO__2725CF03E5446801");

                    b.HasIndex(new[] { "GiaTriKc" }, "UQ__KICHCO__27E03D26500303C4")
                        .IsUnique();

                    b.ToTable("KICHCO");
                });

            modelBuilder.Entity("ShopGiay.Models.Loaigiay", b =>
                {
                    b.Property<int>("MaLg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLg"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLg")
                        .HasName("PK__LOAIGIAY__2725C77E89E2F000");

                    b.ToTable("LOAIGIAY");
                });

            modelBuilder.Entity("ShopGiay.Models.Mathang", b =>
                {
                    b.Property<int>("MaMh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMh"));

                    b.Property<int?>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("GiaGoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LuotMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaLg")
                        .HasColumnType("int")
                        .HasColumnName("MaLG");

                    b.Property<int>("MaTh")
                        .HasColumnType("int")
                        .HasColumnName("MaTH");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMh")
                        .HasName("PK__MATHANG__2725DF398F26F1C4");

                    b.HasIndex("MaLg");

                    b.HasIndex("MaTh");

                    b.ToTable("MATHANG");
                });

            modelBuilder.Entity("ShopGiay.Models.Mausac", b =>
                {
                    b.Property<int>("MaMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaMS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMs"));

                    b.Property<string>("MaHex")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMs")
                        .HasName("PK__MAUSAC__2725DFD64440CB33");

                    b.ToTable("MAUSAC");
                });

            modelBuilder.Entity("ShopGiay.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaCv")
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNv")
                        .HasName("PK__NHANVIEN__2725D70AA0F35AFF");

                    b.HasIndex("MaCv");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("ShopGiay.Models.Thuonghieu", b =>
                {
                    b.Property<int>("MaTh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTh"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTh")
                        .HasName("PK__THUONGHI__27250075C1AF4225");

                    b.HasIndex(new[] { "Ten" }, "UQ__THUONGHI__C451FA833D94F80E")
                        .IsUnique();

                    b.ToTable("THUONGHIEU");
                });

            modelBuilder.Entity("ShopGiay.Models.Tonkho", b =>
                {
                    b.Property<int>("MaK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaK"));

                    b.Property<int?>("GiaBanBt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("GiaBanBT");

                    b.Property<int?>("GiaGocBt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("GiaGocBT");

                    b.Property<int>("MaKc")
                        .HasColumnType("int")
                        .HasColumnName("MaKC");

                    b.Property<int>("MaMh")
                        .HasColumnType("int");

                    b.Property<int>("MaMs")
                        .HasColumnType("int")
                        .HasColumnName("MaMS");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SKU");

                    b.Property<short?>("SoLuongTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("MaK")
                        .HasName("PK__TONKHO__C7977BADD28F2A89");

                    b.HasIndex("MaKc");

                    b.HasIndex("MaMs");

                    b.HasIndex(new[] { "MaMh", "MaMs", "MaKc" }, "UQ__TONKHO__5770A70A3C9A8A51")
                        .IsUnique();

                    b.HasIndex(new[] { "Sku" }, "UQ__TONKHO__CA1ECF0D1F5F9D69")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("TONKHO");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopGiay.Models.Cthoadon", b =>
                {
                    b.HasOne("ShopGiay.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaHD__66603565");

                    b.HasOne("ShopGiay.Models.Tonkho", "MaKNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaK")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaK__6754599E");

                    b.HasOne("ShopGiay.Models.Kichco", "MaKcNavigation")
                        .WithMany()
                        .HasForeignKey("MaKc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopGiay.Models.Mathang", "MaMhNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaMh")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaMh__68487DD7");

                    b.HasOne("ShopGiay.Models.Mausac", "MaMsNavigation")
                        .WithMany()
                        .HasForeignKey("MaMs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaKNavigation");

                    b.Navigation("MaKcNavigation");

                    b.Navigation("MaMhNavigation");

                    b.Navigation("MaMsNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Danhgium", b =>
                {
                    b.HasOne("ShopGiay.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__MaKH__6EF57B66");

                    b.HasOne("ShopGiay.Models.Mathang", "MaMhNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("MaMh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__MaMh__6E01572D");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaMhNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Diachi", b =>
                {
                    b.HasOne("ShopGiay.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Diachis")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__DIACHI__MaKH__5BE2A6F2");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Hoadon", b =>
                {
                    b.HasOne("ShopGiay.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKH__619B8048");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Mathang", b =>
                {
                    b.HasOne("ShopGiay.Models.Loaigiay", "MaLgNavigation")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaLg")
                        .IsRequired()
                        .HasConstraintName("FK__MATHANG__MaLG__44FF419A");

                    b.HasOne("ShopGiay.Models.Thuonghieu", "MaThNavigation")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaTh")
                        .IsRequired()
                        .HasConstraintName("FK__MATHANG__MaTH__45F365D3");

                    b.Navigation("MaLgNavigation");

                    b.Navigation("MaThNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Nhanvien", b =>
                {
                    b.HasOne("ShopGiay.Models.Chucvu", "MaCvNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaCv")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__MaCV__571DF1D5");

                    b.Navigation("MaCvNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Tonkho", b =>
                {
                    b.HasOne("ShopGiay.Models.Kichco", "MaKcNavigation")
                        .WithMany("Tonkhos")
                        .HasForeignKey("MaKc")
                        .IsRequired()
                        .HasConstraintName("FK__TONKHO__MaKC__4E88ABD4");

                    b.HasOne("ShopGiay.Models.Mathang", "MaMhNavigation")
                        .WithMany("Tonkhos")
                        .HasForeignKey("MaMh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TONKHO__MaMh__4CA06362");

                    b.HasOne("ShopGiay.Models.Mausac", "MaMsNavigation")
                        .WithMany("Tonkhos")
                        .HasForeignKey("MaMs")
                        .IsRequired()
                        .HasConstraintName("FK__TONKHO__MaMS__4D94879B");

                    b.Navigation("MaKcNavigation");

                    b.Navigation("MaMhNavigation");

                    b.Navigation("MaMsNavigation");
                });

            modelBuilder.Entity("ShopGiay.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("ShopGiay.Models.Hoadon", b =>
                {
                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("ShopGiay.Models.Khachhang", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Diachis");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("ShopGiay.Models.Kichco", b =>
                {
                    b.Navigation("Tonkhos");
                });

            modelBuilder.Entity("ShopGiay.Models.Loaigiay", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("ShopGiay.Models.Mathang", b =>
                {
                    b.Navigation("Cthoadons");

                    b.Navigation("Danhgia");

                    b.Navigation("Tonkhos");
                });

            modelBuilder.Entity("ShopGiay.Models.Mausac", b =>
                {
                    b.Navigation("Tonkhos");
                });

            modelBuilder.Entity("ShopGiay.Models.Thuonghieu", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("ShopGiay.Models.Tonkho", b =>
                {
                    b.Navigation("Cthoadons");
                });
#pragma warning restore 612, 618
        }
    }
}
